FROM golang:1.23-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/api ./cmd/api

FROM alpine:3.20
WORKDIR /srv
COPY --from=build /bin/api /usr/local/bin/api
COPY --from=build /app/migrations /srv/migrations
COPY --from=build /app/web /srv/web
EXPOSE 8080
CMD ["api"]
